language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm test
after_success:
  - echo all seems to be good!
deploy:
  - provider: script
    script: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git master
    on:
      branch: master
  - provider: script
    script: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD.git production:master
    on:
      branch: production